load("@crates//:crates.bzl", "aliases", "crate_deps")
load("@rules_dx//quality:fixtures.bzl", "real_source_target")
load("//rust/rules:defs.bzl", "rust_binary", "rust_clippy_test", "rustfmt_test")
load("//tools/visibility:visibility.bzl", "VIS_PUBLIC")

package(default_visibility = VIS_PUBLIC)

exports_files(["Cargo.toml"])

rust_binary(
    name = "doctor",
    testonly = False,
    srcs = ["src/bin_doctor.rs"],
    aliases = aliases(
        package_name = "env/env_stubs",
        normal = True,
    ),
    crate_name = "doctor",
    crate_root = "src/bin_doctor.rs",
    edition = "2021",
    deps = crate_deps(
        [],
        package_name = "env/env_stubs",
    ),
)

rust_binary(
    name = "tool_sh",
    testonly = False,
    srcs = ["src/bin_tool.rs"],
    aliases = aliases(
        package_name = "env/env_stubs",
        normal = True,
    ),
    crate_name = "tool_sh",
    crate_root = "src/bin_tool.rs",
    edition = "2021",
    deps = crate_deps(
        [],
        package_name = "env/env_stubs",
    ),
)

rustfmt_test(
    name = "env_stubs_fmt_test",
    size = "small",
    targets = [
        ":doctor",
        ":tool_sh",
    ],
)

rust_clippy_test(
    name = "env_stubs_clippy_test",
    size = "small",
    targets = [
        ":doctor",
        ":tool_sh",
    ],
)

real_source_target(
    name = "corpus_starlark",
    testonly = True,
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)

real_source_target(
    name = "corpus_toml",
    testonly = True,
    tags = ["corpus"],
    toml_srcs = ["Cargo.toml"],
)
