load("@rules_dx//quality:fixtures.bzl", "real_source_target")

exports_files([
    "aspect_rules_py_site_packages.patch",
    "aspect_rules_py_venv_interpreter.patch",
    "rules_ruby_windows_download_host.patch",
])

real_source_target(
    name = "corpus_starlark",
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)
