"""JVM foundation pins (Java, Kotlin, Scala managed route)."""

load(":versions.bzl", _RULES_JAVA_VERSION = "RULES_JAVA_VERSION", _RULES_JVM_EXTERNAL_VERSION = "RULES_JVM_EXTERNAL_VERSION", _RULES_KOTLIN_VERSION = "RULES_KOTLIN_VERSION", _RULES_SCALA_VERSION = "RULES_SCALA_VERSION", _SCALA_VERSION = "SCALA_VERSION")

RULES_JAVA_VERSION = _RULES_JAVA_VERSION
RULES_KOTLIN_VERSION = _RULES_KOTLIN_VERSION
RULES_SCALA_VERSION = _RULES_SCALA_VERSION
SCALA_VERSION = _SCALA_VERSION
RULES_JVM_EXTERNAL_VERSION = _RULES_JVM_EXTERNAL_VERSION

MAVEN_LOCK = "//third_party/jvm:maven_install.json"
MAVEN_REPIN = "REPIN=1 bazel run @maven//:pin"

JVM_TOOL_VERSIONS = {
    "google-java-format": "1.35.0",
    "checkstyle": "14.1.0",
    "pmd": "7.27.0",
    "spotbugs": "4.10.4",
    "ktfmt": "0.63",
    "ktlint": "1.8.0",
}

JAVA_MAJOR = "21"
JAVA_RUNTIME_VERSION = "remotejdk_" + JAVA_MAJOR
