"""JavaScript/TypeScript foundation pins plus npm hubs."""

load(":versions.bzl", _ASPECT_RULES_JEST_VERSION = "ASPECT_RULES_JEST_VERSION", _ASPECT_RULES_JS_VERSION = "ASPECT_RULES_JS_VERSION", _ASPECT_RULES_TS_VERSION = "ASPECT_RULES_TS_VERSION", _NODE_VERSION_PREFIX = "NODE_VERSION_PREFIX", _PNPM_VERSION = "PNPM_VERSION", _TYPESCRIPT_INTEGRITY = "TYPESCRIPT_INTEGRITY", _TYPESCRIPT_VERSION = "TYPESCRIPT_VERSION")

ASPECT_RULES_JS_VERSION = _ASPECT_RULES_JS_VERSION
ASPECT_RULES_TS_VERSION = _ASPECT_RULES_TS_VERSION
ASPECT_RULES_JEST_VERSION = _ASPECT_RULES_JEST_VERSION
TYPESCRIPT_VERSION = _TYPESCRIPT_VERSION
TYPESCRIPT_INTEGRITY = _TYPESCRIPT_INTEGRITY
PNPM_VERSION = _PNPM_VERSION
NODE_VERSION_PREFIX = _NODE_VERSION_PREFIX

NPM_HUBS = ["npm", "npm_tools"]
NPM_LOCKS = [
    "//:pnpm-lock.yaml",
    "//quality/tools/javascript:pnpm-lock.yaml",
]

NPM_REPIN = "bazel run @pnpm//:pnpm -- update"
