"""Shared toolchain pins plus registration order."""

load(":versions.bzl", _BAZEL_SKYLIB_VERSION = "BAZEL_SKYLIB_VERSION", _GAZELLE_VERSION = "GAZELLE_VERSION", _GOOGLETEST_VERSION = "GOOGLETEST_VERSION", _GO_LANGUAGE_FLOOR = "GO_LANGUAGE_FLOOR", _GO_SDK_SDKS = "GO_SDK_SDKS", _GO_SDK_VERSION = "GO_SDK_VERSION", _PLATFORMS_VERSION = "PLATFORMS_VERSION", _RULES_CC_VERSION = "RULES_CC_VERSION", _RULES_GO_VERSION = "RULES_GO_VERSION", _RULES_PROTO_VERSION = "RULES_PROTO_VERSION", _RULES_SHELL_VERSION = "RULES_SHELL_VERSION")

RULES_CC_VERSION = _RULES_CC_VERSION
GOOGLETEST_VERSION = _GOOGLETEST_VERSION
RULES_GO_VERSION = _RULES_GO_VERSION
GAZELLE_VERSION = _GAZELLE_VERSION
RULES_SHELL_VERSION = _RULES_SHELL_VERSION
PLATFORMS_VERSION = _PLATFORMS_VERSION
BAZEL_SKYLIB_VERSION = _BAZEL_SKYLIB_VERSION
RULES_PROTO_VERSION = _RULES_PROTO_VERSION
GO_SDK_VERSION = _GO_SDK_VERSION

GO_LANGUAGE_FLOOR = _GO_LANGUAGE_FLOOR

GO_SDK_SDKS = _GO_SDK_SDKS

DX_TOOL_PLATFORMS = [
    "linux_x86_64",
    "linux_arm64",
    "macos_arm64",
    "windows_arm64",
    "windows_x86_64",
]
