load("//modules:java-scala-kotlin.bzl", "JAVA_MAJOR")
load("//quality:fixtures.bzl", "real_source_target")
load("//tools/ide:ide_acquisition.bzl", "ide_acquisition_test")

package(default_visibility = ["//:__subpackages__"])

# buildifier: disable=canonical-repository
ide_acquisition_test(
    name = "ide_acquisition_test",
    arm64_binary = "@@rules_java++toolchains+remotejdk21_linux_aarch64//:bin/java",
    binary = "@@rules_java++toolchains+remotejdk21_linux//:bin/java",
    expected = JAVA_MAJOR + ".",
    version_args = ["-version"],
)

real_source_target(
    name = "corpus_starlark",
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)
