"""Layer-2 full-matrix runner tests (snapshot workflow)."""

load("//deploy/rules:launcher.bzl", "rlocation_path")
load("//libs/starlark:canonical.bzl", "is_canonical", "strip_canonical")
load("//rust/toolchains:bindings.bzl", "rust_toolchain_toolchains", "rust_toolchain_tools")

def _single_file(target):
    files = target[DefaultInfo].files.to_list()
    if len(files) != 1:
        fail("runner_matrix_test: target '" + str(target.label) + "' must provide exactly one file")
    return files[0]

def _tool_executable(target):
    exe = target[DefaultInfo].files_to_run.executable
    if exe != None:
        return exe
    return _single_file(target)

def _mapping(ctx, ws_path, f):
    return {"key": rlocation_path(ctx, f), "workspace": ws_path}

def _tool_env_entry(entry):
    tool, sep, rest = entry.partition("=")
    if sep == "":
        fail("runner_matrix_test: malformed tool_env '" + entry + "': want TOOL=KEY=VALUE")
    key, key_sep, value = rest.partition("=")
    if key_sep == "":
        fail("runner_matrix_test: malformed tool_env '" + entry + "': want TOOL=KEY=VALUE")
    return {"key": key, "tool": tool, "value": value}

def _runner_matrix_test_impl(ctx):
    harness = ctx.executable._harness
    runner = ctx.executable._runner
    printer = ctx.executable._printer

    staged = {}
    for f in ctx.files.srcs:
        staged[f.short_path] = f
    for ws_path in ctx.attr.generated:
        staged[ws_path] = ctx.actions.declare_file(
            ctx.label.name + "_gen/" + ws_path.replace("/", "__").replace("..", "__"),
        )
        ctx.actions.write(output = staged[ws_path], content = ctx.attr.generated[ws_path])
    sibling_staged = {}
    for f in ctx.files.siblings:
        sibling_staged[f.short_path] = f

    tools = {}
    for i, name in enumerate(ctx.attr.tool_names):
        tools[name] = _tool_executable(ctx.attr.tool_binaries[i])
    if ctx.attr.rustfmt_from_toolchain:
        if "rustfmt" in tools:
            fail("runner_matrix_test: rustfmt_from_toolchain with an explicit rustfmt binary")
        _clippy_driver, rustfmt = rust_toolchain_tools(ctx)
        tools["rustfmt"] = rustfmt

    tool_files = []
    for i, tool in enumerate(ctx.attr.toolfile_tools):
        f = _single_file(ctx.attr.toolfile_srcs[i])
        tool_files.append((tool, f.short_path, f))
    configs = {}
    for i, tool in enumerate(ctx.attr.config_tools):
        configs[tool] = _single_file(ctx.attr.config_files[i]).short_path
    editions = {}
    for i, tool in enumerate(ctx.attr.edition_tools):
        editions[tool] = ctx.attr.edition_values[i]

    upstream = []
    upstream_src_targets = ctx.attr.upstream_srcs
    for i, tool in enumerate(ctx.attr.upstream_tools):
        if i < len(upstream_src_targets):
            upstream.append((tool, _single_file(upstream_src_targets[i])))
        elif tool not in ctx.attr.upstream_generated:
            fail("runner_matrix_test: upstream tool '" + tool + "' has neither upstream_srcs nor upstream_generated bytes")
    for tool, content in ctx.attr.upstream_generated.items():
        if tool in [t for (t, _f) in upstream]:
            fail("runner_matrix_test: duplicate upstream diagnostics for tool '" + tool + "'")
        diagnostics = ctx.actions.declare_file(ctx.label.name + "_gen/upstream/" + tool + ".diagnostics")
        ctx.actions.write(output = diagnostics, content = content)
        upstream.append((tool, diagnostics))

    expected = ctx.file.expected_file
    if expected == None:
        if not ctx.attr.expected:
            fail("runner_matrix_test: either expected or expected_file must be set")
        expected = ctx.actions.declare_file(ctx.label.name + "_expected.txt")
        ctx.actions.write(output = expected, content = ctx.attr.expected)
    elif ctx.attr.expected:
        fail("runner_matrix_test: expected and expected_file are mutually exclusive")

    producer = str(ctx.label)
    if is_canonical(producer):
        producer = strip_canonical(producer)

    manifest_sources = [_mapping(ctx, ws_path, f) for ws_path, f in staged.items()]
    manifest_siblings = [_mapping(ctx, ws_path, f) for ws_path, f in sibling_staged.items()]

    manifest_tools = {}
    for tool in tools.keys():
        manifest_tools[tool] = {
            "binary_key": rlocation_path(ctx, tools[tool]),
            "env": [],
            "files": [],
            "upstream_keys": [],
        }
    for tool, rel, f in tool_files:
        if tool not in manifest_tools:
            manifest_tools[tool] = {"env": [], "files": [], "upstream_keys": []}
        manifest_tools[tool]["files"].append({"key": rlocation_path(ctx, f), "mirror_rel": rel})
    for tool, rel in configs.items():
        if tool not in manifest_tools:
            manifest_tools[tool] = {"env": [], "files": [], "upstream_keys": []}
        manifest_tools[tool]["config"] = rel
    for tool, edition in editions.items():
        if tool not in manifest_tools:
            manifest_tools[tool] = {"env": [], "files": [], "upstream_keys": []}
        manifest_tools[tool]["edition"] = edition

    launcher_env = []
    for launcher in ["pydoclint", "flake8", "pylint"]:
        if launcher in tools:
            launcher_env.append({"key": "RUNFILES_DIR", "tool": launcher, "value": "$TEST_SRCDIR"})
    for launcher in ["eslint", "prettier"]:
        if launcher in tools:
            launcher_env.append({"key": "JS_BINARY__NO_CD_BINDIR", "tool": launcher, "value": "1"})
    for entry in ctx.attr.tool_env:
        launcher_env.append(_tool_env_entry(entry))
    for entry in launcher_env:
        tool = entry["tool"]
        if tool not in manifest_tools:
            manifest_tools[tool] = {"env": [], "files": [], "upstream_keys": []}
        manifest_tools[tool]["env"].append({"key": entry["key"], "value": entry["value"]})
    for tool, f in upstream:
        if tool not in manifest_tools:
            manifest_tools[tool] = {"env": [], "files": [], "upstream_keys": []}
        manifest_tools[tool]["upstream_keys"].append(rlocation_path(ctx, f))

    manifest = {
        "capability": ctx.attr.capability,
        "expected_key": rlocation_path(ctx, expected),
        "name": ctx.label.name,
        "printer_key": rlocation_path(ctx, printer),
        "producer": producer,
        "runner_key": rlocation_path(ctx, runner),
        "schema_version": 1,
        "siblings": manifest_siblings,
        "sources": manifest_sources,
        "stages": ctx.attr.stages,
        "tools": manifest_tools,
        "update_file": ctx.label.name + ".expected.update",
        "update_hint": "quality/testdata/matrix/" + ctx.label.name + ".expected.txt",
    }
    manifest_file = ctx.actions.declare_file(ctx.label.name + ".matrix_manifest.json")
    ctx.actions.write(output = manifest_file, content = json.encode(manifest) + "\n")

    executable = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.symlink(output = executable, target_file = harness, is_executable = True)

    runfiles = ctx.runfiles(
        files = (
            [harness, runner, printer, expected, manifest_file] +
            list(staged.values()) +
            list(sibling_staged.values()) +
            list(tools.values()) +
            [f for (_tool, _rel, f) in tool_files] +
            [f for f in ctx.files.config_files] +
            [f for (_tool, f) in upstream]
        ),
    )
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    for target in (
        ctx.attr.srcs +
        ctx.attr.siblings +
        ctx.attr.tool_binaries +
        ctx.attr.toolfile_srcs +
        ctx.attr.config_files +
        ctx.attr.upstream_srcs +
        [ctx.attr._runner, ctx.attr._printer, ctx.attr._harness]
    ):
        if DefaultInfo in target:
            runfiles = runfiles.merge(target[DefaultInfo].default_runfiles)
    return [
        DefaultInfo(executable = executable, runfiles = runfiles),
        testing.TestEnvironment({"MATRIX_HARNESS_MANIFEST": rlocation_path(ctx, manifest_file)}, []),
    ]

_runner_matrix_test = rule(
    implementation = _runner_matrix_test_impl,
    test = True,
    toolchains = rust_toolchain_toolchains(),
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
        ),
        "generated": attr.string_dict(),
        "siblings": attr.label_list(
            allow_files = True,
        ),
        "capability": attr.string(
            mandatory = True,
            values = ["lint", "format", "typecheck"],
        ),
        "stages": attr.string_list(
            mandatory = True,
        ),
        "tool_names": attr.string_list(),
        "tool_binaries": attr.label_list(),
        "toolfile_tools": attr.string_list(),
        "toolfile_srcs": attr.label_list(
            allow_files = True,
        ),
        "config_tools": attr.string_list(),
        "config_files": attr.label_list(
            allow_files = True,
        ),
        "edition_tools": attr.string_list(),
        "edition_values": attr.string_list(),
        "tool_env": attr.string_list(),
        "upstream_tools": attr.string_list(),
        "upstream_srcs": attr.label_list(
            allow_files = True,
        ),
        "upstream_generated": attr.string_dict(),
        "expected": attr.string(
            default = "",
        ),
        "expected_file": attr.label(
            allow_single_file = True,
        ),
        "rustfmt_from_toolchain": attr.bool(
            default = False,
        ),
        "_runner": attr.label(
            default = "//quality/runner:quality_runner",
            executable = True,
            cfg = "target",
        ),
        "_printer": attr.label(
            default = "//quality/result:print_result",
            executable = True,
            cfg = "target",
        ),
        "_harness": attr.label(
            default = "//quality/runner:matrix_harness",
            executable = True,
            cfg = "target",
        ),
        "_runfiles_lib": attr.label(
            default = "@rules_shell//shell/runfiles",
        ),
    },
)

def runner_matrix_suite(name, cases):
    """Instantiates one _runner_matrix_test per matrix case plus a suite."""
    tests = []
    for case in cases:
        _runner_matrix_test(
            name = case["name"],
            srcs = case.get("srcs", []),
            generated = case.get("generated", {}),
            siblings = case.get("siblings", []),
            capability = case["capability"],
            stages = case["stages"],
            tool_names = case.get("tool_names", []),
            tool_binaries = case.get("tool_binaries", []),
            rustfmt_from_toolchain = case.get("rustfmt_from_toolchain", False),
            toolfile_tools = case.get("toolfile_tools", []),
            toolfile_srcs = case.get("toolfile_srcs", []),
            config_tools = case.get("config_tools", []),
            config_files = case.get("config_files", []),
            edition_tools = case.get("edition_tools", []),
            edition_values = case.get("edition_values", []),
            tool_env = case.get("tool_env", []),
            upstream_tools = case.get("upstream_tools", []),
            upstream_srcs = case.get("upstream_srcs", []),
            upstream_generated = case.get("upstream_generated", {}),
            expected = case.get("expected", ""),
            expected_file = case.get("expected_file"),
            tags = ["no-coverage"],
            target_compatible_with = ["@platforms//os:linux", "@platforms//cpu:x86_64"],
        )
        tests.append(":" + case["name"])
    native.test_suite(name = name, tests = tests)
