"""Layer-2 full-matrix runner tests (snapshot workflow)."""

load("//deploy/rules:launcher.bzl", "rlocation_path")
load("//libs/starlark:canonical.bzl", "is_canonical", "strip_canonical")
load("//libs/starlark:wrapper.bzl", "dx_symlink_executable")
load("//rust/toolchains:bindings.bzl", "rust_toolchain_toolchains", "rust_toolchain_tools")

def _single_file(target):
    files = target[DefaultInfo].files.to_list()
    if len(files) != 1:
        fail("runner_matrix_test: target '" + str(target.label) + "' must provide exactly one file")
    return files[0]

def _tool_executable(target):
    exe = target[DefaultInfo].files_to_run.executable
    if exe != None:
        return exe
    return _single_file(target)

def _tool_env(spec):
    """Splits one tool=KEY=VALUE entry into its manifest fields."""
    tool, sep, rest = spec.partition("=")
    key, value_sep, value = rest.partition("=")
    if sep == "" or value_sep == "" or tool == "" or key == "":
        fail("runner_matrix_test: tool_env entry '" + spec + "' must read tool=KEY=VALUE")
    return {"tool": tool, "key": key, "value": {"value": value}}

def _runner_matrix_test_impl(ctx):
    runner = ctx.executable._runner
    printer = ctx.executable._printer

    staged = {}  # workspace path -> File staged as its bytes
    for f in ctx.files.srcs:
        staged[f.short_path] = f
    for ws_path in ctx.attr.generated:
        staged[ws_path] = ctx.actions.declare_file(
            ctx.label.name + "_gen/" + ws_path.replace("/", "__").replace("..", "__"),
        )
        ctx.actions.write(output = staged[ws_path], content = ctx.attr.generated[ws_path])
    sibling_staged = {}
    for f in ctx.files.siblings:
        sibling_staged[f.short_path] = f

    tools = {}  # tool name -> binary File
    for i, name in enumerate(ctx.attr.tool_names):
        tools[name] = _tool_executable(ctx.attr.tool_binaries[i])
    if ctx.attr.rustfmt_from_toolchain:
        if "rustfmt" in tools:
            fail("runner_matrix_test: rustfmt_from_toolchain with an explicit rustfmt binary")
        _clippy_driver, rustfmt = rust_toolchain_tools(ctx)
        tools["rustfmt"] = rustfmt

    tool_files = []  # (tool, rel, File)
    for i, tool in enumerate(ctx.attr.toolfile_tools):
        f = _single_file(ctx.attr.toolfile_srcs[i])
        tool_files.append((tool, f.short_path, f))
    configs = []  # (tool, rel)
    for i, tool in enumerate(ctx.attr.config_tools):
        configs.append((tool, _single_file(ctx.attr.config_files[i]).short_path))
    editions = []  # (tool, edition)
    for i, tool in enumerate(ctx.attr.edition_tools):
        editions.append((tool, ctx.attr.edition_values[i]))

    upstream = []  # (tool, File)
    upstream_src_targets = ctx.attr.upstream_srcs
    for i, tool in enumerate(ctx.attr.upstream_tools):
        if i < len(upstream_src_targets):
            upstream.append((tool, _single_file(upstream_src_targets[i])))
        elif tool not in ctx.attr.upstream_generated:
            fail("runner_matrix_test: upstream tool '" + tool + "' has neither upstream_srcs nor upstream_generated bytes")
    for tool, content in ctx.attr.upstream_generated.items():
        if tool in [t for (t, _f) in upstream]:
            fail("runner_matrix_test: duplicate upstream diagnostics for tool '" + tool + "'")
        diagnostics = ctx.actions.declare_file(ctx.label.name + "_gen/upstream/" + tool + ".diagnostics")
        ctx.actions.write(output = diagnostics, content = content)
        upstream.append((tool, diagnostics))

    expected = ctx.file.expected_file
    if expected == None:
        if not ctx.attr.expected:
            fail("runner_matrix_test: either expected or expected_file must be set")
        expected = ctx.actions.declare_file(ctx.label.name + "_expected.txt")
        ctx.actions.write(output = expected, content = ctx.attr.expected)
    elif ctx.attr.expected:
        fail("runner_matrix_test: expected and expected_file are mutually exclusive")

    producer = str(ctx.label)
    if is_canonical(producer):
        producer = strip_canonical(producer)

    tool_env = []
    for launcher in ["pydoclint", "flake8", "pylint"]:
        if launcher in tools:
            tool_env.append({
                "tool": launcher,
                "key": "RUNFILES_DIR",
                "value": {"runfiles_root": True},
            })
    for launcher in ["eslint", "prettier"]:
        if launcher in tools:
            tool_env.append({
                "tool": launcher,
                "key": "JS_BINARY__NO_CD_BINDIR",
                "value": {"value": "1"},
            })
    for spec in ctx.attr.tool_env:
        tool_env.append(_tool_env(spec))

    manifest = {
        "schema_version": 1,
        "name": ctx.label.name,
        "producer": producer,
        "capability": ctx.attr.capability,
        "stages": ctx.attr.stages,
        "runner": rlocation_path(ctx, runner),
        "printer": rlocation_path(ctx, printer),
        "expected": rlocation_path(ctx, expected),
        "snapshot_dir": "quality/testdata/matrix",
        "sources": [{"workspace": ws, "rlocation": rlocation_path(ctx, f)} for ws, f in staged.items()],
        "siblings": [{"workspace": ws, "rlocation": rlocation_path(ctx, f)} for ws, f in sibling_staged.items()],
        "tools": [{"tool": tool, "rlocation": rlocation_path(ctx, f)} for tool, f in tools.items()],
        "tool_configs": [{"tool": tool, "config": rel} for tool, rel in configs],
        "tool_editions": [{"tool": tool, "edition": edition} for tool, edition in editions],
        "tool_files": [{"tool": tool, "rel": rel, "rlocation": rlocation_path(ctx, f)} for tool, rel, f in tool_files],
        "tool_env": tool_env,
        "upstream": [{"tool": tool, "rlocation": rlocation_path(ctx, f)} for tool, f in upstream],
    }
    manifest_file = ctx.actions.declare_file(ctx.label.name + ".manifest.json")
    ctx.actions.write(output = manifest_file, content = json.encode(manifest))
    executable = dx_symlink_executable(ctx, ctx.executable._harness)

    runfiles = ctx.runfiles(
        files = (
            [executable, runner, printer, expected, manifest_file, ctx.executable._harness] +
            list(staged.values()) +
            list(sibling_staged.values()) +
            list(tools.values()) +
            [f for (_tool, _rel, f) in tool_files] +
            list(ctx.files.config_files) +
            [f for (_tool, f) in upstream]
        ),
    )
    for target in (
        ctx.attr.srcs +
        ctx.attr.siblings +
        ctx.attr.tool_binaries +
        ctx.attr.toolfile_srcs +
        ctx.attr.config_files +
        ctx.attr.upstream_srcs +
        [ctx.attr._runner, ctx.attr._printer, ctx.attr._harness]
    ):
        if DefaultInfo in target:
            runfiles = runfiles.merge(target[DefaultInfo].default_runfiles)
    return [
        DefaultInfo(
            executable = executable,
            runfiles = runfiles,
        ),
        testing.TestEnvironment(
            {"DX_MATRIX_MANIFEST": rlocation_path(ctx, manifest_file)},
            [],
        ),
    ]

_runner_matrix_test = rule(
    implementation = _runner_matrix_test_impl,
    test = True,
    toolchains = rust_toolchain_toolchains(),
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
        ),
        "generated": attr.string_dict(),
        "siblings": attr.label_list(
            allow_files = True,
        ),
        "capability": attr.string(
            mandatory = True,
            values = ["lint", "format", "typecheck"],
        ),
        "stages": attr.string_list(
            mandatory = True,
        ),
        "tool_names": attr.string_list(),
        "tool_binaries": attr.label_list(),
        "toolfile_tools": attr.string_list(),
        "toolfile_srcs": attr.label_list(
            allow_files = True,
        ),
        "config_tools": attr.string_list(),
        "config_files": attr.label_list(
            allow_files = True,
        ),
        "edition_tools": attr.string_list(),
        "edition_values": attr.string_list(),
        "tool_env": attr.string_list(),
        "upstream_tools": attr.string_list(),
        "upstream_srcs": attr.label_list(
            allow_files = True,
        ),
        "upstream_generated": attr.string_dict(),
        "expected": attr.string(
            default = "",
        ),
        "expected_file": attr.label(
            allow_single_file = True,
        ),
        "rustfmt_from_toolchain": attr.bool(
            default = False,
        ),
        "_runner": attr.label(
            default = "//quality/runner:quality_runner",
            executable = True,
            cfg = "target",
        ),
        "_printer": attr.label(
            default = "//quality/result:print_result",
            executable = True,
            cfg = "target",
        ),
        "_harness": attr.label(
            default = "//quality/matrix:matrix_harness",
            executable = True,
            cfg = "target",
        ),
    },
)

def runner_matrix_suite(name, cases):
    """Instantiates one _runner_matrix_test per matrix case plus a suite."""
    tests = []
    for case in cases:
        _runner_matrix_test(
            name = case["name"],
            srcs = case.get("srcs", []),
            generated = case.get("generated", {}),
            siblings = case.get("siblings", []),
            capability = case["capability"],
            stages = case["stages"],
            tool_names = case.get("tool_names", []),
            tool_binaries = case.get("tool_binaries", []),
            rustfmt_from_toolchain = case.get("rustfmt_from_toolchain", False),
            toolfile_tools = case.get("toolfile_tools", []),
            toolfile_srcs = case.get("toolfile_srcs", []),
            config_tools = case.get("config_tools", []),
            config_files = case.get("config_files", []),
            edition_tools = case.get("edition_tools", []),
            edition_values = case.get("edition_values", []),
            tool_env = case.get("tool_env", []),
            upstream_tools = case.get("upstream_tools", []),
            upstream_srcs = case.get("upstream_srcs", []),
            upstream_generated = case.get("upstream_generated", {}),
            expected = case.get("expected", ""),
            expected_file = case.get("expected_file"),
            tags = ["no-coverage"],
            target_compatible_with = ["@platforms//os:linux", "@platforms//cpu:x86_64"],
        )
        tests.append(":" + case["name"])
    native.test_suite(name = name, tests = tests)
