load("//quality:fixtures.bzl", "real_source_target")
load(":metadata_tests.bzl", "android_metadata_tests")

package(default_visibility = ["//visibility:public"])

exports_files([
    "metadata_tests.bzl",
    "repos.bzl",
])

android_metadata_tests(name = "metadata")

real_source_target(
    name = "corpus_starlark",
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = [
        "BUILD.bazel",
        "metadata_tests.bzl",
        "repos.bzl",
    ],
    tags = ["corpus"],
)
