load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "consumer_c",
    srcs = ["hello.c"],
    hdrs = ["hello.h"],
)

cc_binary(
    name = "consumer_c_bin",
    srcs = ["main.c"],
    deps = [":consumer_c"],
)

cc_test(
    name = "consumer_c_test",
    srcs = ["hello_test.c"],
    deps = [":consumer_c"],
)
