load("@rules_python//python:defs.bzl", "py_binary")
load("//quality:fixtures.bzl", "real_source_target")
load("//tools/visibility:visibility.bzl", "VIS_QUALITY")
load(":corpus_tests.bzl", "corpus_coverage_test")
load(":metadata_tests.bzl", "metadata_tests")
load(":platforms_tests.bzl", "platforms_tests")

package(default_visibility = VIS_QUALITY)

py_binary(
    name = "update",
    srcs = ["update.py"],
    main = "update.py",
)

exports_files(glob(
    ["*.bzl"],
    exclude = [
        "extension.bzl",
        "metadata_tests.bzl",
    ],
))

exports_files(
    ["update.py"],
    visibility = [
        "//quality:__pkg__",
        "//quality:__subpackages__",
        "//tools/ci:__pkg__",
    ],
)

metadata_tests(name = "metadata")

platforms_tests(name = "platforms")

corpus_coverage_test(
    name = "corpus_coverage",
    subject = ":corpus_starlark",
)

test_suite(
    name = "all",
    tests = [
        ":corpus_coverage",
        ":metadata",
        ":platforms",
        "//quality/artifacts/acquire_test",
        "//quality/artifacts/hub_test:hub_selection_analysis",
        "//quality/artifacts/hub_test:hub_selection_unit",
    ],
)

real_source_target(
    name = "corpus_python",
    aspect_hints = ["//:ruff_config"],
    python_srcs = glob(["*.py"]),
    tags = ["corpus"],
)

real_source_target(
    name = "corpus_starlark",
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = ["BUILD.bazel"] + glob(["*.bzl"]),
    tags = ["corpus"],
)
