"""dx_tools use_repo inventory."""

DX_TOOL_REPOS = [

    "dx_biome_linux_arm64",
    "dx_biome_linux_x86_64",
    "dx_biome_macos_arm64",
    "dx_biome_windows_arm64",
    "dx_biome_windows_x86_64",
    "dx_buildifier_linux_arm64",
    "dx_buildifier_linux_x86_64",
    "dx_buildifier_macos_arm64",
    "dx_buildifier_windows_arm64",
    "dx_buildifier_windows_x86_64",
    "dx_gitleaks_linux_arm64",
    "dx_gitleaks_linux_x86_64",
    "dx_gitleaks_macos_arm64",
    "dx_gitleaks_windows_arm64",
    "dx_gitleaks_windows_x86_64",
    "dx_gofumpt_linux_arm64",
    "dx_gofumpt_linux_x86_64",
    "dx_gofumpt_macos_arm64",
    "dx_gofumpt_windows_x86_64",
    "dx_ruff_linux_arm64",
    "dx_ruff_linux_x86_64",
    "dx_ruff_macos_arm64",
    "dx_ruff_windows_arm64",
    "dx_ruff_windows_x86_64",
    "dx_shellcheck_linux_arm64",
    "dx_shellcheck_linux_x86_64",
    "dx_shellcheck_macos_arm64",
    "dx_shfmt_linux_arm64",
    "dx_shfmt_linux_x86_64",
    "dx_shfmt_macos_arm64",
    "dx_shfmt_windows_x86_64",
    "dx_staticcheck_linux_arm64",
    "dx_staticcheck_linux_x86_64",
    "dx_staticcheck_macos_arm64",
    "dx_staticcheck_windows_x86_64",
    "dx_taplo_linux_arm64",
    "dx_taplo_linux_x86_64",
    "dx_taplo_macos_arm64",
    "dx_taplo_windows_arm64",
    "dx_taplo_windows_x86_64",
    "dx_ty_linux_arm64",
    "dx_ty_linux_x86_64",
    "dx_ty_macos_arm64",
    "dx_ty_windows_arm64",
    "dx_ty_windows_x86_64",
    "dx_vale_linux_arm64",
    "dx_vale_linux_x86_64",
    "dx_vale_macos_arm64",
    "dx_vale_windows_arm64",
    "dx_vale_windows_x86_64",

]

DX_TOOL_HUB = "dx_tools"
