load("//quality:fixtures.bzl", "real_source_target")
load("//tools/visibility:visibility.bzl", "VIS_PUBLIC")

package(default_visibility = VIS_PUBLIC)

alias(
    name = "mdbook",
    actual = "@dx_mdbook//:mdbook",
)

exports_files(["repos.bzl"])

real_source_target(
    name = "corpus_starlark",
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = [
        "BUILD.bazel",
        "repos.bzl",
    ],
    tags = ["corpus"],
)
