load("@rules_dx//cc/rules:defs.bzl", "cc_binary", "cc_library")
load("//quality:fixtures.bzl", "real_source_target")

package(default_visibility = ["//:__subpackages__"])

cc_binary(
    name = "shapes_main",
    srcs = ["shapes_main.cc"],
    deps = [":shapes"],
)

cc_library(
    name = "shapes",
    srcs = ["shapes.cc"],
    hdrs = ["shapes.h"],
)

real_source_target(
    name = "corpus_starlark",
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)
